spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db?currentSchema=public
    username: rad_admin
    password: rad_admin
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public